### PR TITLE
Restyle answer questions

### PR DESCRIPTION
**Pull request by badrihippo**
Styling has been updated to almost match that proposed by the Design Team (available in Google Docs).

Some things yet to be implemented:

* The breadcrumb/"back to dashboard" button needs to be implemented system-wide in `base.html`
* "Previous"/"Next" buttons, for which the view will have to return the relevant links
* Editor toolbar does not look exactly like the Gmail one (which was copied for the proposed Sawaliram design). The main change required is a drop-down menu to hold extra options
* Info icon has been added providing information about what will happen once the piece was submitted. This could possibly be moved to a "success page" or a pre-submission popup in the future
* "Save Draft" button currently does same action as "Submit" button: view is not yet able to handle drafts.

Additionally, the toolbar takes up too much of the screen space. We need to decide a way to hide/compress this once the user scrolls up (and maybe the design team should decide how this would look).

### CODE REVIEW

**Comment by badrihippo** [comment]
Ignore the last point about the toolbar: it's been fixed in later iterations of the design. Just realised I was trying to use an earlier version 😛

**Comment by nitinpaul** [comment]
Hey Badri! Thanks for the PR, the page works as intended :D We're very close to closing this one, let me clarify your points:
1. Breadcrumbs are dropped from the design for now, so no worries on that front. 
2. We'll set up the next/prev links in a later commit. We'll have to think of a strategy for implementing this. The user will see a list of questions she wants to answer, maybe applies some filters to refine the list, selects one question to answer, goes to the editor (this view), and then the Next/Prev buttons should cycle through that list. I have an idea for it, but I don't know if it's the right one. Let's discuss this!
3. The editor toolbar need not look like the one in the design, it's just there for reference. The current toolbar is neat and clean :)
4. The info icon can be dropped, we have a message system in place - check out `SubmitQuestionsView` for an example.
5. It'd be cool if you can figure out drafts, it can be as simple as saving the state in a table! I think that's how it is supposed to be since the Drafts will be available in the User Profile later. We can use some AJAX magic for it, checkout `processSelectedExcelSheet()` in our `scripts.js`.

Additionally, these are some things that needs fixing:
1. The Prev/Next bar at the top has a `box-shadow` in the design
2. We talked about using class-based views. Accordingly, all other views have been updated. It's not much of work, take a look at the examples in `views.py`
3. The URLs have been updated to be more 'REST-like'. I suggest something like '/question/{id}/submit-answer'.
4. Instead of the accept answer function, is it better if I send you test datasets? One file with 50 sample questions from actual data and another with the curation done. You can submit the first file at 'Submit Questions' and upload the second one at 'Manage Content' and you'll have 50 sample datapoints ready to go!
5. The styling for `.highlighted-meta-area` seems to be missing
6. We can drop the `<hr>` elements, best give the toolbar a `border-bottom`, to make it compact.

Yes, the massive header is not the most compact design choice, but for v1, let's stick to the design and not get sidetracked!

**Comment by badrihippo** [comment]
All points noted.

- [ ] Drafts is still a bit complicated because we need a separate interface to select it, etc. Let's discuss in Zulip first and then come back here?
- [x] Info icon replaced with `messages`-powered notification
- [x] `box-shadow` added; take a look and let me know if the amount/value is okay
- [  ] `accept_answer` function: datasets is fine for now, but the function would be useful in the future as well. Suppose I wanted to quickly mark one question as curated while testing, or something, I could just call this instead of manually typing all those `question.value = unanswered_question.value` lines.
- [x] Class-based views activated successfully
- [x] URL changed to `/dashboard/question/<id>/answer/new`. We can use a similar structure to edit questions, etc. in future.
- [ ] `.highlighted-meta-area` styles don't seem to be missing: check again? I think I moved it around to a different place though.
- [x] `<hr>`s replaced with `border` styling—not sure if it's elegant enough, but it does the job.

**Comment by badrihippo** [comment]
Resolves #58

**Comment by badrihippo** [comment]
Fixes #58.

**Pull request merged**
